/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef face_CONSTANTS_H
#define face_CONSTANTS_H

#include "face_types.h"



class faceConstants {
 public:
  faceConstants();

};

extern const faceConstants g_face_constants;



#endif
