// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Videoface.proto

#include "Videoface.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class VideoFacePictureDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VideoFacePicture>
      _instance;
} _VideoFacePicture_default_instance_;
namespace protobuf_Videoface_2eproto {
static void InitDefaultsVideoFacePicture() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_VideoFacePicture_default_instance_;
    new (ptr) ::VideoFacePicture();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::VideoFacePicture::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_VideoFacePicture =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVideoFacePicture}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_VideoFacePicture.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFacePicture, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFacePicture, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFacePicture, face_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFacePicture, face_img_),
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::VideoFacePicture)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_VideoFacePicture_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "Videoface.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017Videoface.proto\"5\n\020VideoFacePicture\022\017\n"
      "\007face_id\030\001 \002(\t\022\020\n\010face_img\030\002 \002(\014"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 72);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Videoface.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_Videoface_2eproto

// ===================================================================

void VideoFacePicture::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VideoFacePicture::kFaceIdFieldNumber;
const int VideoFacePicture::kFaceImgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VideoFacePicture::VideoFacePicture()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Videoface_2eproto::scc_info_VideoFacePicture.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:VideoFacePicture)
}
VideoFacePicture::VideoFacePicture(const VideoFacePicture& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  face_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_face_id()) {
    face_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_id_);
  }
  face_img_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_face_img()) {
    face_img_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_img_);
  }
  // @@protoc_insertion_point(copy_constructor:VideoFacePicture)
}

void VideoFacePicture::SharedCtor() {
  face_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_img_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

VideoFacePicture::~VideoFacePicture() {
  // @@protoc_insertion_point(destructor:VideoFacePicture)
  SharedDtor();
}

void VideoFacePicture::SharedDtor() {
  face_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_img_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void VideoFacePicture::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* VideoFacePicture::descriptor() {
  ::protobuf_Videoface_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Videoface_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VideoFacePicture& VideoFacePicture::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Videoface_2eproto::scc_info_VideoFacePicture.base);
  return *internal_default_instance();
}


void VideoFacePicture::Clear() {
// @@protoc_insertion_point(message_clear_start:VideoFacePicture)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      face_id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      face_img_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool VideoFacePicture::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:VideoFacePicture)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string face_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_face_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->face_id().data(), static_cast<int>(this->face_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "VideoFacePicture.face_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bytes face_img = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_face_img()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:VideoFacePicture)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:VideoFacePicture)
  return false;
#undef DO_
}

void VideoFacePicture::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:VideoFacePicture)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string face_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->face_id().data(), static_cast<int>(this->face_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "VideoFacePicture.face_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->face_id(), output);
  }

  // required bytes face_img = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->face_img(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:VideoFacePicture)
}

::google::protobuf::uint8* VideoFacePicture::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:VideoFacePicture)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string face_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->face_id().data(), static_cast<int>(this->face_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "VideoFacePicture.face_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->face_id(), target);
  }

  // required bytes face_img = 2;
  if (cached_has_bits & 0x00000002u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->face_img(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VideoFacePicture)
  return target;
}

size_t VideoFacePicture::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:VideoFacePicture)
  size_t total_size = 0;

  if (has_face_id()) {
    // required string face_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->face_id());
  }

  if (has_face_img()) {
    // required bytes face_img = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->face_img());
  }

  return total_size;
}
size_t VideoFacePicture::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:VideoFacePicture)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string face_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->face_id());

    // required bytes face_img = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->face_img());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VideoFacePicture::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:VideoFacePicture)
  GOOGLE_DCHECK_NE(&from, this);
  const VideoFacePicture* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VideoFacePicture>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:VideoFacePicture)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:VideoFacePicture)
    MergeFrom(*source);
  }
}

void VideoFacePicture::MergeFrom(const VideoFacePicture& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:VideoFacePicture)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_face_id();
      face_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_id_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_face_img();
      face_img_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_img_);
    }
  }
}

void VideoFacePicture::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:VideoFacePicture)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VideoFacePicture::CopyFrom(const VideoFacePicture& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VideoFacePicture)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VideoFacePicture::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void VideoFacePicture::Swap(VideoFacePicture* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VideoFacePicture::InternalSwap(VideoFacePicture* other) {
  using std::swap;
  face_id_.Swap(&other->face_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  face_img_.Swap(&other->face_img_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata VideoFacePicture::GetMetadata() const {
  protobuf_Videoface_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Videoface_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::VideoFacePicture* Arena::CreateMaybeMessage< ::VideoFacePicture >(Arena* arena) {
  return Arena::CreateInternal< ::VideoFacePicture >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
