// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Videoface.proto

#ifndef PROTOBUF_INCLUDED_Videoface_2eproto
#define PROTOBUF_INCLUDED_Videoface_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Videoface_2eproto 

namespace protobuf_Videoface_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Videoface_2eproto
class VideoFacePicture;
class VideoFacePictureDefaultTypeInternal;
extern VideoFacePictureDefaultTypeInternal _VideoFacePicture_default_instance_;
namespace google {
namespace protobuf {
template<> ::VideoFacePicture* Arena::CreateMaybeMessage<::VideoFacePicture>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class VideoFacePicture : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:VideoFacePicture) */ {
 public:
  VideoFacePicture();
  virtual ~VideoFacePicture();

  VideoFacePicture(const VideoFacePicture& from);

  inline VideoFacePicture& operator=(const VideoFacePicture& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VideoFacePicture(VideoFacePicture&& from) noexcept
    : VideoFacePicture() {
    *this = ::std::move(from);
  }

  inline VideoFacePicture& operator=(VideoFacePicture&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VideoFacePicture& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VideoFacePicture* internal_default_instance() {
    return reinterpret_cast<const VideoFacePicture*>(
               &_VideoFacePicture_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(VideoFacePicture* other);
  friend void swap(VideoFacePicture& a, VideoFacePicture& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VideoFacePicture* New() const final {
    return CreateMaybeMessage<VideoFacePicture>(NULL);
  }

  VideoFacePicture* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<VideoFacePicture>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const VideoFacePicture& from);
  void MergeFrom(const VideoFacePicture& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoFacePicture* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string face_id = 1;
  bool has_face_id() const;
  void clear_face_id();
  static const int kFaceIdFieldNumber = 1;
  const ::std::string& face_id() const;
  void set_face_id(const ::std::string& value);
  #if LANG_CXX11
  void set_face_id(::std::string&& value);
  #endif
  void set_face_id(const char* value);
  void set_face_id(const char* value, size_t size);
  ::std::string* mutable_face_id();
  ::std::string* release_face_id();
  void set_allocated_face_id(::std::string* face_id);

  // required bytes face_img = 2;
  bool has_face_img() const;
  void clear_face_img();
  static const int kFaceImgFieldNumber = 2;
  const ::std::string& face_img() const;
  void set_face_img(const ::std::string& value);
  #if LANG_CXX11
  void set_face_img(::std::string&& value);
  #endif
  void set_face_img(const char* value);
  void set_face_img(const void* value, size_t size);
  ::std::string* mutable_face_img();
  ::std::string* release_face_img();
  void set_allocated_face_img(::std::string* face_img);

  // @@protoc_insertion_point(class_scope:VideoFacePicture)
 private:
  void set_has_face_id();
  void clear_has_face_id();
  void set_has_face_img();
  void clear_has_face_img();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr face_id_;
  ::google::protobuf::internal::ArenaStringPtr face_img_;
  friend struct ::protobuf_Videoface_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VideoFacePicture

// required string face_id = 1;
inline bool VideoFacePicture::has_face_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void VideoFacePicture::set_has_face_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void VideoFacePicture::clear_has_face_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void VideoFacePicture::clear_face_id() {
  face_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_face_id();
}
inline const ::std::string& VideoFacePicture::face_id() const {
  // @@protoc_insertion_point(field_get:VideoFacePicture.face_id)
  return face_id_.GetNoArena();
}
inline void VideoFacePicture::set_face_id(const ::std::string& value) {
  set_has_face_id();
  face_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:VideoFacePicture.face_id)
}
#if LANG_CXX11
inline void VideoFacePicture::set_face_id(::std::string&& value) {
  set_has_face_id();
  face_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:VideoFacePicture.face_id)
}
#endif
inline void VideoFacePicture::set_face_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_face_id();
  face_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:VideoFacePicture.face_id)
}
inline void VideoFacePicture::set_face_id(const char* value, size_t size) {
  set_has_face_id();
  face_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:VideoFacePicture.face_id)
}
inline ::std::string* VideoFacePicture::mutable_face_id() {
  set_has_face_id();
  // @@protoc_insertion_point(field_mutable:VideoFacePicture.face_id)
  return face_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VideoFacePicture::release_face_id() {
  // @@protoc_insertion_point(field_release:VideoFacePicture.face_id)
  if (!has_face_id()) {
    return NULL;
  }
  clear_has_face_id();
  return face_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VideoFacePicture::set_allocated_face_id(::std::string* face_id) {
  if (face_id != NULL) {
    set_has_face_id();
  } else {
    clear_has_face_id();
  }
  face_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), face_id);
  // @@protoc_insertion_point(field_set_allocated:VideoFacePicture.face_id)
}

// required bytes face_img = 2;
inline bool VideoFacePicture::has_face_img() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void VideoFacePicture::set_has_face_img() {
  _has_bits_[0] |= 0x00000002u;
}
inline void VideoFacePicture::clear_has_face_img() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void VideoFacePicture::clear_face_img() {
  face_img_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_face_img();
}
inline const ::std::string& VideoFacePicture::face_img() const {
  // @@protoc_insertion_point(field_get:VideoFacePicture.face_img)
  return face_img_.GetNoArena();
}
inline void VideoFacePicture::set_face_img(const ::std::string& value) {
  set_has_face_img();
  face_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:VideoFacePicture.face_img)
}
#if LANG_CXX11
inline void VideoFacePicture::set_face_img(::std::string&& value) {
  set_has_face_img();
  face_img_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:VideoFacePicture.face_img)
}
#endif
inline void VideoFacePicture::set_face_img(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_face_img();
  face_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:VideoFacePicture.face_img)
}
inline void VideoFacePicture::set_face_img(const void* value, size_t size) {
  set_has_face_img();
  face_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:VideoFacePicture.face_img)
}
inline ::std::string* VideoFacePicture::mutable_face_img() {
  set_has_face_img();
  // @@protoc_insertion_point(field_mutable:VideoFacePicture.face_img)
  return face_img_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VideoFacePicture::release_face_img() {
  // @@protoc_insertion_point(field_release:VideoFacePicture.face_img)
  if (!has_face_img()) {
    return NULL;
  }
  clear_has_face_img();
  return face_img_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VideoFacePicture::set_allocated_face_img(::std::string* face_img) {
  if (face_img != NULL) {
    set_has_face_img();
  } else {
    clear_has_face_img();
  }
  face_img_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), face_img);
  // @@protoc_insertion_point(field_set_allocated:VideoFacePicture.face_img)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Videoface_2eproto
